#!/bin/bash

# Clones the 100 first repositories for a given user in Github.

# Warning! If more than 100 repositories exist change the PAGE.

USER=$1
PAGE=1

curl "https://api.github.com/users/$USER/repos?page=$PAGE&per_page=100" |
  grep -e 'git_url*' |
  cut -d \" -f 4 |
  xargs -L1 git clone