#!/bin/sh


# This script creates a new git repository to the directory it was executed
# and also publishes it to Github as a remote.

# Arguments: Github user name and 

# example initPublish User RepoName

#Github account name
GITHUB_USERNAME=$1
REPO_NAME=$2

###############################################################################
###     Create new Github repository
###############################################################################

# Check arguments to be a valid
test -z $GITHUB_USERNAME && echo "A Github username is required." 1>&2 && exit 1
test -z $REPO_NAME       && echo "A repository name is required." 1>&2 && exit 1

# Create the repository throught the Github API.
curl -u "$GITHUB_USERNAME" https://api.github.com/user/repos -d "{\"name\":\"$REPO_NAME\"}"

###############################################################################
###     Create local repository
###############################################################################

git init
git add --all
git commit -m "First commit"

###############################################################################
###     Connext local with remote and publish
###############################################################################

git remote add origin "https://github.com/$GITHUB_USERNAME/$REPO_NAME.git"
git remote -v
git push origin master

echo Finished...
